// @/database/db.ts

import { Word, Idiom, GrammarQuestion, Quote } from '../types';

// This file contains the entire content library for the application.
// By centralizing the data here, we make the app fast, reliable, and offline-first.

export const DB = {
  words: [
    // --- EASY ---
    { term: 'benevolent', definition: 'Well meaning and kindly.', synonyms: ['kind', 'charitable', 'magnanimous'], antonyms: ['malevolent', 'spiteful', 'cruel'], example: 'A benevolent donor paid for the new hospital wing.', difficulty: 'Easy' },
    { term: 'clarify', definition: 'To make something clear or easier to understand.', synonyms: ['explain', 'elucidate', 'simplify'], antonyms: ['confuse', 'obfuscate', 'muddy'], example: 'Could you clarify your instructions, please?', difficulty: 'Easy' },
    { term: 'diligent', definition: 'Showing care and conscientiousness in one\'s work or duties.', synonyms: ['hardworking', 'assiduous', 'industrious'], antonyms: ['lazy', 'negligent', 'careless'], example: 'She was a diligent student who always did her homework.', difficulty: 'Easy' },
    { term: 'essential', definition: 'Absolutely necessary; extremely important.', synonyms: ['crucial', 'vital', 'indispensable'], antonyms: ['unnecessary', 'optional', 'secondary'], example: 'Water is essential for life.', difficulty: 'Easy' },
    { term: 'flexible', definition: 'Able to change or be changed easily according to the situation.', synonyms: ['adaptable', 'pliable', 'versatile'], antonyms: ['rigid', 'inflexible', 'stiff'], example: 'Our travel plans are flexible.', difficulty: 'Easy' },
    { term: 'gregarious', definition: 'Fond of company; sociable.', synonyms: ['sociable', 'convivial', 'outgoing'], antonyms: ['introverted', 'reclusive', 'shy'], example: 'Her gregarious nature made her the life of every party.', difficulty: 'Easy' },
    { term: 'honest', definition: 'Free of deceit and untruthfulness; sincere.', synonyms: ['truthful', 'sincere', 'frank'], antonyms: ['dishonest', 'deceitful', 'insincere'], example: 'He gave an honest answer to the difficult question.', difficulty: 'Easy' },
    { term: 'innovate', definition: 'To introduce something new, especially a new method or idea.', synonyms: ['create', 'invent', 'pioneer'], antonyms: ['copy', 'stagnate', 'follow'], example: 'The company that does not innovate will fail.', difficulty: 'Easy' },
    { term: 'joyful', definition: 'Feeling, expressing, or causing great pleasure and happiness.', synonyms: ['happy', 'elated', 'jubilant'], antonyms: ['sad', 'miserable', 'depressed'], example: 'It was a joyful reunion of old friends.', difficulty: 'Easy' },
    { term: 'keen', definition: 'Having or showing eagerness or enthusiasm.', synonyms: ['eager', 'enthusiastic', 'avid'], antonyms: ['apathetic', 'indifferent', 'reluctant'], example: 'He is a keen supporter of the local football team.', difficulty: 'Easy' },

    // --- MEDIUM ---
    { term: 'alacrity', definition: 'Brisk and cheerful readiness.', synonyms: ['eagerness', 'enthusiasm', 'promptness'], antonyms: ['apathy', 'reluctance', 'slowness'], example: 'She accepted the invitation with alacrity.', difficulty: 'Medium' },
    { term: 'capricious', definition: 'Given to sudden and unaccountable changes of mood or behavior.', synonyms: ['fickle', 'mercurial', 'volatile'], antonyms: ['stable', 'consistent', 'predictable'], example: 'The capricious weather made it difficult to plan the picnic.', difficulty: 'Medium' },
    { term: 'ephemeral', definition: 'Lasting for a very short time.', synonyms: ['transient', 'fleeting', 'momentary'], antonyms: ['permanent', 'enduring', 'eternal'], example: 'The beauty of the cherry blossoms is ephemeral, lasting only for a week.', difficulty: 'Medium' },
    { term: 'fastidious', definition: 'Very attentive to and concerned about accuracy and detail.', synonyms: ['meticulous', 'scrupulous', 'punctilious'], antonyms: ['careless', 'sloppy', 'lax'], example: 'He was fastidious about keeping his workspace perfectly organized.', difficulty: 'Medium' },
    { term: 'garrulous', definition: 'Excessively talkative, especially on trivial matters.', synonyms: ['loquacious', 'talkative', 'verbose'], antonyms: ['taciturn', 'reticent', 'concise'], example: 'The garrulous taxi driver talked nonstop for the entire ride.', difficulty: 'Medium' },
    { term: 'juxtaposition', definition: 'The fact of two things being seen or placed close together with contrasting effect.', synonyms: ['comparison', 'contrast', 'collocation'], antonyms: ['separation', 'distance', 'remoteness'], example: 'The juxtaposition of old and new architecture was striking.', difficulty: 'Medium' },
    { term: 'myriad', definition: 'A countless or extremely great number.', synonyms: ['countless', 'innumerable', 'multitude'], antonyms: ['few', 'limited', 'countable'], example: 'The night sky was filled with a myriad of stars.', difficulty: 'Medium' },
    { term: 'serendipity', definition: 'The occurrence of events by chance in a happy or beneficial way.', synonyms: ['fluke', 'chance', 'happy accident'], antonyms: ['misfortune', 'bad luck', 'calamity'], example: 'Discovering the hidden cafe was a moment of pure serendipity.', difficulty: 'Medium' },
    { term: 'taciturn', definition: 'Reserved or uncommunicative in speech; saying little.', synonyms: ['uncommunicative', 'reticent', 'quiet'], antonyms: ['talkative', 'garrulous', 'loquacious'], example: 'The new student was taciturn and rarely spoke in class.', difficulty: 'Medium' },
    { term: 'ubiquitous', definition: 'Present, appearing, or found everywhere.', synonyms: ['omnipresent', 'pervasive', 'universal'], antonyms: ['rare', 'scarce', 'infrequent'], example: 'Smartphones have become ubiquitous in modern society.', difficulty: 'Medium' },
    { term: 'veracity', definition: 'Conformity to facts; accuracy.', synonyms: ['truthfulness', 'accuracy', 'correctness'], antonyms: ['falsehood', 'inaccuracy', 'deceit'], example: 'The lawyer questioned the veracity of the witness\'s statement.', difficulty: 'Medium' },
    { term: 'wanderlust', definition: 'A strong desire to travel.', synonyms: ['desire to travel', 'love of travel', 'itchy feet'], antonyms: ['homebody', 'stay-at-home', 'settler'], example: 'Her wanderlust led her to explore over fifty countries.', difficulty: 'Medium' },

    // --- HARD ---
    { term: 'aberration', definition: 'A departure from what is normal, usual, or expected, typically unwelcome.', synonyms: ['anomaly', 'deviation', 'irregularity'], antonyms: ['normality', 'regularity', 'conformity'], example: 'The single poor grade was an aberration in her otherwise stellar academic record.', difficulty: 'Hard' },
    { term: 'cacophony', definition: 'A harsh, discordant mixture of sounds.', synonyms: ['din', 'racket', 'clamor'], antonyms: ['euphony', 'harmony', 'quiet'], example: 'The construction site was filled with the cacophony of heavy machinery.', difficulty: 'Hard' },
    { term: 'diaphanous', definition: 'Light, delicate, and translucent.', synonyms: ['sheer', 'gossamer', 'transparent'], antonyms: ['opaque', 'thick', 'heavy'], example: 'The bride wore a diaphanous veil.', difficulty: 'Hard' },
    { term: 'ebullient', definition: 'Cheerful and full of energy.', synonyms: ['exuberant', 'buoyant', 'chipper'], antonyms: ['depressed', 'lethargic', 'apathetic'], example: 'She was in an ebullient mood after receiving the good news.', difficulty: 'Hard' },
    { term: 'insidious', definition: 'Proceeding in a gradual, subtle way, but with harmful effects.', synonyms: ['stealthy', 'sly', 'treacherous'], antonyms: ['open', 'honest', 'straightforward'], example: 'Procrastination is an insidious habit that can slowly ruin your productivity.', difficulty: 'Hard' },
    { term: 'kowtow', definition: 'Act in an excessively subservient manner.', synonyms: ['grovel', 'fawn', 'sycophant'], antonyms: ['defy', 'resist', 'challenge'], example: 'The employees were expected to kowtow to the demanding CEO.', difficulty: 'Hard' },
    { term: 'mellifluous', definition: 'A sound that is sweet and smooth, pleasing to hear.', synonyms: ['euphonious', 'melodious', 'dulcet'], antonyms: ['cacophonous', 'harsh', 'grating'], example: 'Her mellifluous voice was perfect for reading audiobooks.', difficulty: 'Hard' },
    { term: 'obfuscate', definition: 'Render obscure, unclear, or unintelligible.', synonyms: ['confuse', 'muddy', 'complicate'], antonyms: ['clarify', 'simplify', 'illuminate'], example: 'The politician tried to obfuscate the issue with irrelevant details.', difficulty: 'Hard' },
    { term: 'pulchritudinous', definition: 'Having great physical beauty.', synonyms: ['beautiful', 'gorgeous', 'stunning'], antonyms: ['ugly', 'hideous', 'unattractive'], example: 'The model was known for her pulchritudinous features.', difficulty: 'Hard' },
    { term: 'rancor', definition: 'Bitterness or resentfulness, especially when long-standing.', synonyms: ['bitterness', 'spite', 'malice'], antonyms: ['goodwill', 'friendliness', 'amity'], example: 'She held a deep rancor towards her former business partner.', difficulty: 'Hard' },
    { term: 'truculent', definition: 'Eager or quick to argue or fight; aggressively defiant.', synonyms: ['defiant', 'aggressive', 'belligerent'], antonyms: ['cooperative', 'amicable', 'peaceful'], example: 'His truculent attitude often got him into trouble.', difficulty: 'Hard' },
    { term: 'unctuous', definition: 'Excessively flattering or ingratiating; oily.', synonyms: ['sycophantic', 'ingratiating', 'smarmy'], antonyms: ['sincere', 'genuine', 'blunt'], example: 'The salesperson\'s unctuous charm made me distrust him immediately.', difficulty: 'Hard' },

    // --- EXAM ---
    { term: 'deleterious', definition: 'Causing harm or damage.', synonyms: ['harmful', 'detrimental', 'injurious'], antonyms: ['beneficial', 'harmless', 'helpful'], example: 'Smoking has a deleterious effect on your health.', difficulty: 'Exam' },
    { term: 'hegemony', definition: 'Leadership or dominance, especially by one country or social group over others.', synonyms: ['dominance', 'supremacy', 'ascendancy'], antonyms: ['subordination', 'powerlessness', 'submission'], example: 'The company asserted its hegemony in the tech industry.', difficulty: 'Exam' },
    { term: 'iconoclast', definition: 'A person who attacks cherished beliefs or institutions.', synonyms: ['critic', 'dissident', 'maverick'], antonyms: ['conformist', 'believer', 'follower'], example: 'The artist was an iconoclast, challenging traditional forms of expression.', difficulty: 'Exam' },
    { term: 'laconic', definition: 'Using very few words.', synonyms: ['brief', 'concise', 'terse'], antonyms: ['verbose', 'loquacious', 'talkative'], example: 'His laconic reply of "fine" told her everything she needed to know.', difficulty: 'Exam' },
    { term: 'maudlin', definition: 'Self-pityingly or tearfully sentimental.', synonyms: ['sentimental', 'emotional', 'weepy'], antonyms: ['stoic', 'unemotional', 'pragmatic'], example: 'The film became maudlin and overly sentimental in its final scenes.', difficulty: 'Exam' },
    { term: 'nefarious', definition: 'Wicked or criminal.', synonyms: ['villainous', 'iniquitous', 'heinous'], antonyms: ['virtuous', 'righteous', 'noble'], example: 'The supervillain hatched a nefarious plot to take over the world.', difficulty: 'Exam' },
    { term: 'panacea', definition: 'A solution or remedy for all difficulties or diseases.', synonyms: ['cure-all', 'elixir', 'universal remedy'], antonyms: ['problem', 'disease', 'ailment'], example: 'He mistakenly believed that technology was a panacea for all of society\'s problems.', difficulty: 'Exam' },
    { term: 'pithy', definition: 'Concise and forcefully expressive.', synonyms: ['terse', 'concise', 'succinct'], antonyms: ['verbose', 'long-winded', 'wordy'], example: 'His pithy comments summed up the situation perfectly.', difficulty: 'Exam' },
    { term: 'quixotic', definition: 'Exceedingly idealistic; unrealistic and impractical.', synonyms: ['idealistic', 'impractical', 'visionary'], antonyms: ['practical', 'realistic', 'pragmatic'], example: 'His quest to build a castle out of toothpicks was a quixotic endeavor.', difficulty: 'Exam' },
    { term: 'sagacious', definition: 'Having or showing keen mental discernment and good judgment.', synonyms: ['wise', 'discerning', 'judicious'], antonyms: ['foolish', 'stupid', 'unwise'], example: 'The sagacious old professor always gave the best advice.', difficulty: 'Exam' },
    { term: 'sycophant', definition: 'A person who acts obsequiously toward someone important to gain advantage.', synonyms: ['flatterer', 'toady', 'lackey'], antonyms: ['leader', 'critic', 'rebel'], example: 'The king was surrounded by sycophants who praised his every decision.', difficulty: 'Exam' },
    { term: 'zeitgeist', definition: 'The defining spirit or mood of a particular period of history.', synonyms: ['spirit of the age', 'climate', 'mood'], antonyms: ['anachronism', 'timelessness', ''], example: 'The band\'s music perfectly captured the zeitgeist of the 1960s.', difficulty: 'Exam' },
  ] as Word[],
  idioms: [
    // --- EASY ---
    { term: 'Bite the bullet', definition: 'To endure a difficult or unpleasant situation with courage.', example: 'He had to bite the bullet and work late to finish the project.', difficulty: 'Easy' },
    { term: 'Break a leg', definition: 'A way to wish someone good luck, especially before a performance.', example: 'Before the play, I told my friend to break a leg.', difficulty: 'Easy' },
    { term: 'Hit the sack', definition: 'To go to bed.', example: 'I\'m exhausted, it\'s time for me to hit the sack.', difficulty: 'Easy' },
    { term: 'Piece of cake', definition: 'Something that is very easy to do.', example: 'The exam was a piece of cake.', difficulty: 'Easy' },
    { term: 'Call it a day', definition: 'To stop working on something.', example: 'We\'ve made enough progress for now, let\'s call it a day.', difficulty: 'Easy' },
    { term: 'Hang in there', definition: 'Don\'t give up.', example: 'I know you\'re tired, but hang in there, you\'re almost finished.', difficulty: 'Easy' },
    { term: 'Under the weather', definition: 'To feel ill.', example: 'I\'m feeling a bit under the weather today, so I\'m staying home.', difficulty: 'Easy' },
    { term: 'Pull someone\'s leg', definition: 'To joke with someone.', example: 'Relax, I\'m just pulling your leg. I didn\'t really break your laptop.', difficulty: 'Easy' },

    // --- MEDIUM ---
    { term: 'Spill the beans', definition: 'To reveal a secret.', example: 'She spilled the beans about the surprise party.', difficulty: 'Medium' },
    { term: 'A blessing in disguise', definition: 'A good thing that seemed bad at first.', example: 'Losing that job was a blessing in disguise; I found a much better one.', difficulty: 'Medium' },
    { term: 'Go back to the drawing board', definition: 'To start over.', example: 'Our initial plan failed, so we have to go back to the drawing board.', difficulty: 'Medium' },
    { term: 'Let the cat out of the bag', definition: 'To accidentally reveal a secret.', example: 'He let the cat out of the bag about their wedding plans.', difficulty: 'Medium' },
    { term: 'On the ball', definition: 'Doing a good job; being alert and efficient.', example: 'Our new intern is really on the ball.', difficulty: 'Medium' },
    { term: 'Beat around the bush', definition: 'To avoid saying what you mean, usually because it is uncomfortable.', example: 'Stop beating around the bush and just tell me what happened.', difficulty: 'Medium' },
    { term: 'Kill two birds with one stone', definition: 'To achieve two things in a single action.', example: 'I can kill two birds with one stone by listening to an English podcast while I exercise.', difficulty: 'Medium' },
    { term: 'The ball is in your court', definition: 'It is up to you to make the next move or decision.', example: 'I\'ve given you my final offer; now the ball is in your court.', difficulty: 'Medium' },

    // --- HARD ---
    { term: 'The best of both worlds', definition: 'An ideal situation.', example: 'Working from home gives me the best of both worlds: a career and time with my family.', difficulty: 'Hard' },
    { term: 'Once in a blue moon', definition: 'Happens very rarely.', example: 'I only go to the opera once in a blue moon.', difficulty: 'Hard' },
    { term: 'The elephant in the room', definition: 'A major problem that is obviously present but avoided as a subject for discussion.', example: 'His gambling addiction was the elephant in the room at every family gathering.', difficulty: 'Hard' },
    { term: 'Cut corners', definition: 'To do something in the easiest, cheapest, or fastest way.', example: 'The company cut corners on safety regulations and now faces a lawsuit.', difficulty: 'Hard' },
    { term: 'Jump on the bandwagon', definition: 'To join a popular activity or trend.', example: 'After the team won the championship, thousands of new fans jumped on the bandwagon.', difficulty: 'Hard' },
    { term: 'Read between the lines', definition: 'To understand the hidden meaning in what is said or written.', example: 'She said she was fine, but reading between the lines, I could tell she was upset.', difficulty: 'Hard' },
    { term: 'Steal someone\'s thunder', definition: 'To take the credit for something someone else did.', example: 'My colleague stole my thunder when he presented my idea to the boss as his own.', difficulty: 'Hard' },

    // --- EXAM ---
    { term: 'A dime a dozen', definition: 'Very common and of no particular value.', example: 'Experts in that field are a dime a dozen.', difficulty: 'Exam' },
    { term: 'Cry over spilt milk', definition: 'To be unhappy about something that cannot be undone.', example: 'It\'s no use crying over spilt milk; the mistake is made and we have to move on.', difficulty: 'Exam' },
    { term: 'Get a taste of your own medicine', definition: 'To be treated in the same unpleasant way you have treated others.', example: 'The bully finally got a taste of his own medicine when the new student stood up to him.', difficulty: 'Exam' },
    { term: 'Let sleeping dogs lie', definition: 'To avoid restarting a conflict or argument.', example: 'I wanted to bring up our old argument, but I decided to let sleeping dogs lie.', difficulty: 'Exam' },
    { term: 'Miss the boat', definition: 'To miss an opportunity.', example: 'The tickets sold out in an hour, and I totally missed the boat.', difficulty: 'Exam' },
    { term: 'Through thick and thin', definition: 'Under all circumstances, no matter how difficult.', example: 'True friends stick together through thick and thin.', difficulty: 'Exam' },
    { term: 'Throw caution to the wind', definition: 'To take a risk.', example: 'She threw caution to the wind and quit her job to start her own business.', difficulty: 'Exam' },
  ] as Idiom[],
  grammar: [
    // --- EASY ---
    { question: 'She ___ to the store every morning.', options: ['go', 'goes', 'is going', 'went'], correctAnswer: 'goes', explanation: '"Goes" is the correct third-person singular present tense form for the subject "She".', difficulty: 'Easy' },
    { question: 'I have been waiting for you ___ an hour.', options: ['since', 'for', 'at', 'in'], correctAnswer: 'for', explanation: '"For" is used to express a duration of time. "Since" is used to refer to a specific point in time.', difficulty: 'Easy' },
    { question: 'My brother is taller ___ me.', options: ['then', 'than', 'as', 'from'], correctAnswer: 'than', explanation: '"Than" is a conjunction used for comparisons, while "then" is an adverb related to time.', difficulty: 'Easy' },
    { question: 'He is very good ___ playing the piano.', options: ['in', 'at', 'on', 'with'], correctAnswer: 'at', explanation: 'The correct preposition to use after "good" to describe a skill is "at".', difficulty: 'Easy' },
    { question: 'I saw ___ amazing movie last night.', options: ['a', 'an', 'the', 'some'], correctAnswer: 'an', explanation: '"An" is used before words that start with a vowel sound, like "amazing".', difficulty: 'Easy' },
    { question: 'The team ___ their best, but they lost the game.', options: ['do', 'does', 'did', 'done'], correctAnswer: 'did', explanation: 'The sentence is in the past tense ("lost"), so the simple past form "did" is required.', difficulty: 'Easy' },
    { question: 'There isn\'t ___ milk left in the fridge.', options: ['some', 'any', 'many', 'a lot'], correctAnswer: 'any', explanation: '"Any" is typically used in negative sentences and questions, while "some" is used in positive sentences.', difficulty: 'Easy' },
    { question: 'Could you please pass me ___ salt?', options: ['a', 'an', 'the', 'any'], correctAnswer: 'the', explanation: '"The" is a definite article used here because it refers to a specific salt shaker that is understood by both speakers.', difficulty: 'Easy' },

    // --- MEDIUM ---
    { question: 'The book is on the table, ___ it?', options: ['is', 'it is', 'isn\'t', 'is not'], correctAnswer: 'isn\'t', explanation: 'This is a tag question. Since the main clause is positive ("The book is..."), the tag must be negative ("...isn\'t it?").', difficulty: 'Medium' },
    { question: 'She has been living here ___ 2010.', options: ['for', 'since', 'from', 'in'], correctAnswer: 'since', explanation: '"Since" is used to mark the starting point of a period of time that continues to the present.', difficulty: 'Medium' },
    { question: 'Each of the students ___ responsible for their own project.', options: ['is', 'are', 'be', 'were'], correctAnswer: 'is', explanation: 'The pronoun "Each" is singular and requires a singular verb, "is".', difficulty: 'Medium' },
    { question: 'I\'m looking forward ___ you again.', options: ['to see', 'seeing', 'to seeing', 'see'], correctAnswer: 'to seeing', explanation: 'The phrase "look forward to" is a phrasal verb and must be followed by a gerund (-ing form).', difficulty: 'Medium' },
    { question: 'The new policy will ___ everyone in the company.', options: ['affect', 'effect', 'affects', 'effects'], correctAnswer: 'affect', explanation: '"Affect" is a verb meaning "to influence". "Effect" is usually a noun meaning "a result".', difficulty: 'Medium' },
    { question: 'He needs to cut ___ on sugary drinks.', options: ['off', 'out', 'down', 'up'], correctAnswer: 'down', explanation: '"Cut down on" is a phrasal verb meaning to reduce the consumption of something.', difficulty: 'Medium' },
    { question: 'The number of students ___ increasing.', options: ['is', 'are', 'has', 'have'], correctAnswer: 'is', explanation: 'The phrase "The number of" is singular and takes a singular verb.', difficulty: 'Medium' },
    { question: 'I would rather ___ at home than go to the party.', options: ['staying', 'to stay', 'stay', 'stayed'], correctAnswer: 'stay', explanation: 'The phrase "would rather" is followed by the base form of the verb (infinitive without "to").', difficulty: 'Medium' },

    // --- HARD ---
    { question: 'If I ___ you, I would take the offer.', options: ['was', 'am', 'were', 'be'], correctAnswer: 'were', explanation: 'In conditional sentences (second conditional), "were" is used for hypothetical situations, even with "I".', difficulty: 'Hard' },
    { question: 'Neither my friends nor my brother ___ the answer.', options: ['know', 'knows', 'is knowing', 'have known'], correctAnswer: 'knows', explanation: 'When using "neither...nor", the verb agrees with the subject closest to it. In this case, "brother" is singular, so we use "knows".', difficulty: 'Hard' },
    { question: 'By the time you arrive, I ___ my homework.', options: ['will finish', 'will have finished', 'am finishing', 'finished'], correctAnswer: 'will have finished', explanation: 'The future perfect tense "will have finished" is used to describe an action that will be completed before another future event.', difficulty: 'Hard' },
    { question: 'I wish I ___ known about the party earlier.', options: ['had', 'have', 'would', 'did'], correctAnswer: 'had', explanation: 'The past perfect "had known" is used after "wish" to express regret about a past event.', difficulty: 'Hard' },
    { question: 'The concert was canceled ___ the heavy rain.', options: ['because', 'due to', 'although', 'in spite of'], correctAnswer: 'due to', explanation: '"Due to" is a preposition used to give the reason for something and is typically followed by a noun phrase ("the heavy rain").', difficulty: 'Hard' },
    { question: 'She is one of the artists who ___ nominated for the award.', options: ['was', 'were', 'is', 'has'], correctAnswer: 'were', explanation: 'The relative pronoun "who" refers to "artists" (plural), so the plural verb "were" is correct.', difficulty: 'Hard' },
    { question: 'Despite ___ tired, he continued to work.', options: ['he was', 'of being', 'being', 'was'], correctAnswer: 'being', explanation: '"Despite" is a preposition and must be followed by a noun or a gerund (-ing form).', difficulty: 'Hard' },

    // --- EXAM ---
    { question: 'If she ___ harder, she would have passed the exam.', options: ['studies', 'had studied', 'studied', 'would study'], correctAnswer: 'had studied', explanation: 'This is a third conditional sentence structure (If + past perfect, ...would have + past participle) used for hypothetical past situations.', difficulty: 'Exam' },
    { question: 'Hardly ___ I stepped out when it started to rain.', options: ['had', 'did', 'have', 'was'], correctAnswer: 'had', explanation: 'When a sentence begins with a negative adverb like "Hardly", we use inversion: "Hardly had I...".', difficulty: 'Exam' },
    { question: 'This is the city ___ I was born.', options: ['which', 'that', 'where', 'who'], correctAnswer: 'where', explanation: '"Where" is a relative adverb used to refer to a place.', difficulty: 'Exam' },
    { question: 'He has ___ money than I do.', options: ['less', 'fewer', 'little', 'few'], correctAnswer: 'less', explanation: '"Less" is used with uncountable nouns like "money". "Fewer" is used with countable nouns.', difficulty: 'Exam' },
    { question: 'You must finish your work ___ you can go out to play.', options: ['after', 'before', 'until', 'while'], correctAnswer: 'before', explanation: '"Before" is a conjunction that indicates something must happen prior to something else.', difficulty: 'Exam' },
    { question: 'He apologized ___ being late.', options: ['of', 'to', 'for', 'with'], correctAnswer: 'for', explanation: 'The correct preposition to use with "apologize" is "for" when giving a reason.', difficulty: 'Exam' },
  ] as GrammarQuestion[],
  quotes: [
    // Quotes do not have difficulty levels
    { quote: "The beautiful thing about learning is that no one can take it away from you.", author: "B.B. King" },
    { quote: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
    { quote: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle" },
    { quote: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
    { quote: "The only person who is educated is the one who has learned how to learn and change.", author: "Carl Rogers" },
    { quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
    { quote: "It is not that I'm so smart. But I stay with the questions much longer.", author: "Albert Einstein" },
    { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { quote: "The expert in anything was once a beginner.", author: "Helen Hayes" },
    { quote: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
    { quote: "Learning is a treasure that will follow its owner everywhere.", author: "Chinese Proverb" },
    { quote: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { quote: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
    { quote: "The mind is not a vessel to be filled, but a fire to be kindled.", author: "Plutarch" },
    { quote: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin" },
    { quote: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
    { quote: "He who opens a school door, closes a prison.", author: "Victor Hugo" },
    { quote: "Education is not preparation for life; education is life itself.", author: "John Dewey" },
    { quote: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
    { quote: "The more that you read, the more things you will know. The more that you learn, the more places you'll go.", author: "Dr. Seuss" },
    { quote: "Learning never exhausts the mind.", author: "Leonardo da Vinci" },
    { quote: "The goal of education is the advancement of knowledge and the dissemination of truth.", author: "John F. Kennedy" },
    { quote: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle" },
    { quote: "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.", author: "Albert Einstein" },
    { quote: "I have no special talent. I am only passionately curious.", author: "Albert Einstein" },
    { quote: "The art of teaching is the art of assisting discovery.", author: "Mark Van Doren" },
    { quote: "Change is the end result of all true learning.", author: "Leo Buscaglia" },
    { quote: "Education's purpose is to replace an empty mind with an open one.", author: "Malcolm Forbes" },
    { quote: "Anyone who stops learning is old, whether at twenty or eighty. Anyone who keeps learning stays young.", author: "Henry Ford" },
    { quote: "The only thing that interferes with my learning is my education.", author: "Albert Einstein" },
    { quote: "Knowledge is power.", author: "Francis Bacon" },
    { quote: "What we learn with pleasure we never forget.", author: "Alfred Mercier" },
    { quote: "The highest result of education is tolerance.", author: "Helen Keller" },
    { quote: "The foundation of every state is the education of its youth.", author: "Diogenes" },
    { quote: "You are always a student, never a master. You have to keep moving forward.", author: "Conrad Hall" },
    { quote: "I am still learning.", author: "Michelangelo" },
    { quote: "Strive for progress, not perfection.", author: "Unknown" },
    { quote: "There is no substitute for hard work.", author: "Thomas Edison" },
    { quote: "Do the best you can until you know better. Then when you know better, do better.", author: "Maya Angelou" },
    { quote: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.", author: "Thomas Edison" },
    { quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { quote: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
    { quote: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison" },
    { quote: "If you can dream it, you can do it.", author: "Walt Disney" },
    { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { quote: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
    { quote: "Either you run the day or the day runs you.", author: "Jim Rohn" },
    { quote: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
    { quote: "The best way to predict the future is to create it.", author: "Peter Drucker" },
    { quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
    { quote: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
    { quote: "You have to be odd to be number one.", author: "Dr. Seuss" },
    { quote: "Fall seven times and stand up eight.", author: "Japanese Proverb" },
    { quote: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
    { quote: "I would rather die of passion than of boredom.", author: "Vincent van Gogh" },
    { quote: "It is never too late to be what you might have been.", author: "George Eliot" },
    { quote: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
    { quote: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { quote: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
    { quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
    { quote: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
    { quote: "The man who has confidence in himself gains the confidence of others.", author: "Hasidic Proverb" },
    { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
    { quote: "The secret of change is to focus all of your energy, not on fighting the old, but on building the new.", author: "Socrates" },
    { quote: "A creative man is motivated by the desire to achieve, not by the desire to beat others.", author: "Ayn Rand" },
    { quote: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
    { quote: "The most difficult thing is the decision to act, the rest is merely tenacity.", author: "Amelia Earhart" },
    { quote: "Whether you think you can or you think you can’t, you’re right.", author: "Henry Ford" },
    { quote: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain" },
    { quote: "Nothing is impossible, the word itself says 'I'm possible'!", author: "Audrey Hepburn" },
    { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { quote: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
    { quote: "All our dreams can come true if we have the courage to pursue them.", author: "Walt Disney" },
    { quote: "Don't let what you cannot do interfere with what you can do.", author: "John Wooden" },
    { quote: "If you're going through hell, keep going.", author: "Winston Churchill" },
    { quote: "In order to succeed, we must first believe that we can.", author: "Nikos Kazantzakis" },
    { quote: "Never bend your head. Always hold it high. Look the world straight in the eye.", author: "Helen Keller" },
    { quote: "What you do today can improve all your tomorrows.", author: "Ralph Marston" },
    { quote: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
  ] as Quote[],
};
