// @/database/idioms.ts
import { Idiom } from '../types';

export const idioms: Idiom[] = [
    // --- EASY ---
    { term: 'Bite the bullet', definition: 'To endure a difficult or unpleasant situation with courage.', example: 'He had to bite the bullet and work late to finish the project.', difficulty: 'Easy' },
    { term: 'Break a leg', definition: 'A way to wish someone good luck, especially before a performance.', example: 'Before the play, I told my friend to break a leg.', difficulty: 'Easy' },
    { term: 'Hit the sack', definition: 'To go to bed.', example: 'I\'m exhausted, it\'s time for me to hit the sack.', difficulty: 'Easy' },
    { term: 'Piece of cake', definition: 'Something that is very easy to do.', example: 'The exam was a piece of cake.', difficulty: 'Easy' },
    { term: 'Call it a day', definition: 'To stop working on something.', example: 'We\'ve made enough progress for now, let\'s call it a day.', difficulty: 'Easy' },
    { term: 'Hang in there', definition: 'Don\'t give up.', example: 'I know you\'re tired, but hang in there, you\'re almost finished.', difficulty: 'Easy' },
    { term: 'Under the weather', definition: 'To feel ill.', example: 'I\'m feeling a bit under the weather today, so I\'m staying home.', difficulty: 'Easy' },
    { term: 'Pull someone\'s leg', definition: 'To joke with someone.', example: 'Relax, I\'m just pulling your leg. I didn\'t really break your laptop.', difficulty: 'Easy' },
    { term: 'Cost an arm and a leg', definition: 'To be very expensive.', example: 'That new car must have cost him an arm and a leg.', difficulty: 'Easy' },
    { term: 'See eye to eye', definition: 'To agree on something.', example: 'My sister and I don\'t see eye to eye on politics.', difficulty: 'Easy' },
    { term: 'When pigs fly', definition: 'Something that will never happen.', example: 'He\'ll clean his room when pigs fly.', difficulty: 'Easy' },
    { term: 'On cloud nine', definition: 'To be extremely happy and excited.', example: 'She\'s been on cloud nine ever since she got engaged.', difficulty: 'Easy' },
    { term: 'Get cold feet', definition: 'To become too frightened to do something you had planned to do.', example: 'He got cold feet and canceled the wedding.', difficulty: 'Easy' },
    { term: 'Rule of thumb', definition: 'A general or approximate rule based on experience or practice.', example: 'As a rule of thumb, you should double the recipe for a large party.', difficulty: 'Easy' },
    { term: 'A hot potato', definition: 'A controversial or sensitive issue that is difficult to handle.', example: 'The topic of tax increases became a political hot potato.', difficulty: 'Easy' },
    { term: 'Every cloud has a silver lining', definition: 'There is something good in every bad situation.', example: 'I was sad when I lost my job, but it gave me a chance to start my own business. Every cloud has a silver lining.', difficulty: 'Easy' },
    { term: 'It\'s raining cats and dogs', definition: 'It\'s raining very heavily.', example: 'I can\'t go for a walk now, it\'s raining cats and dogs outside.', difficulty: 'Easy' },
    { term: 'Fit as a fiddle', definition: 'To be in very good health.', example: 'My grandfather is 90 years old, but he is fit as a fiddle.', difficulty: 'Easy' },
    { term: 'A penny for your thoughts', definition: 'A way of asking what someone is thinking.', example: 'You\'ve been quiet for a while. A penny for your thoughts?', difficulty: 'Easy' },
    { term: 'Actions speak louder than words', definition: 'What you do is more important and shows your true intentions more than what you say.', example: 'He keeps promising to help, but actions speak louder than words.', difficulty: 'Easy' },
    { term: 'Jump to conclusions', definition: 'To make a decision about something too quickly, without knowing all the facts.', example: 'Don\'t jump to conclusions! You don\'t know the whole story.', difficulty: 'Easy' },
    { term: 'Get out of hand', definition: 'To become difficult to control.', example: 'The party started to get out of hand, so we called the police.', difficulty: 'Easy' },
    { term: 'Let someone off the hook', definition: 'To allow someone to escape from a difficult situation or from a responsibility.', example: 'I\'ll let you off the hook this time, but don\'t be late again.', difficulty: 'Easy' },
    { term: 'Better late than never', definition: 'It is better to do something late than not at all.', example: 'He finally paid me back the money he owed me. Well, better late than never.', difficulty: 'Easy' },

    // --- MEDIUM ---
    { term: 'Spill the beans', definition: 'To reveal a secret.', example: 'She spilled the beans about the surprise party.', difficulty: 'Medium' },
    { term: 'A blessing in disguise', definition: 'A good thing that seemed bad at first.', example: 'Losing that job was a blessing in disguise; I found a much better one.', difficulty: 'Medium' },
    { term: 'Go back to the drawing board', definition: 'To start over.', example: 'Our initial plan failed, so we have to go back to the drawing board.', difficulty: 'Medium' },
    { term: 'Let the cat out of the bag', definition: 'To accidentally reveal a secret.', example: 'He let the cat out of the bag about their wedding plans.', difficulty: 'Medium' },
    { term: 'On the ball', definition: 'Doing a good job; being alert and efficient.', example: 'Our new intern is really on the ball.', difficulty: 'Medium' },
    { term: 'Beat around the bush', definition: 'To avoid saying what you mean, usually because it is uncomfortable.', example: 'Stop beating around the bush and just tell me what happened.', difficulty: 'Medium' },
    { term: 'Kill two birds with one stone', definition: 'To achieve two things in a single action.', example: 'I can kill two birds with one stone by listening to an English podcast while I exercise.', difficulty: 'Medium' },
    { term: 'The ball is in your court', definition: 'It is up to you to make the next move or decision.', example: 'I\'ve given you my final offer; now the ball is in your court.', difficulty: 'Medium' },
    { term: 'Bite off more than you can chew', definition: 'To try to do something that is too difficult for you.', example: 'He bit off more than he could chew by taking on three projects at once.', difficulty: 'Medium' },
    { term: 'Add insult to injury', definition: 'To make a bad situation even worse.', example: 'My car broke down, and to add insult to injury, it started to rain.', difficulty: 'Medium' },
    { term: 'Barking up the wrong tree', definition: 'To pursue a mistaken course of action; to be wrong about something.', example: 'If you think I\'m responsible for the error, you\'re barking up the wrong tree.', difficulty: 'Medium' },
    { term: 'Face the music', definition: 'To accept criticism or punishment for something you have done.', example: 'After he was caught cheating, he had to face the music.', difficulty: 'Medium' },
    { term: 'A chip on your shoulder', definition: 'To seem angry all the time because you think you have been treated unfairly.', example: 'He has a chip on his shoulder about not getting the promotion.', difficulty: 'Medium' },
    { term: 'Go the extra mile', definition: 'To make a special effort to achieve something.', example: 'She always goes the extra mile for her customers.', difficulty: 'Medium' },
    { term: 'Cut to the chase', definition: 'To get to the point without wasting time.', example: 'I don\'t have much time, so let\'s cut to the chase.', difficulty: 'Medium' },
    { term: 'Down to the wire', definition: 'Something that ends at the last minute or last moment.', example: 'The game went down to the wire; it was a tie until the final second.', difficulty: 'Medium' },
    { term: 'Hear it on the grapevine', definition: 'To hear rumors about something or someone.', example: 'I heard on the grapevine that she\'s getting a promotion.', difficulty: 'Medium' },
    { term: 'Hit the nail on the head', definition: 'To describe exactly what is causing a situation or problem.', example: 'You really hit the nail on the head with that analysis.', difficulty: 'Medium' },
    { term: 'Sit on the fence', definition: 'To avoid making a decision or choice.', example: 'You can\'t sit on the fence any longer; you need to choose a side.', difficulty: 'Medium' },
    { term: 'Take with a grain of salt', definition: 'To not take what someone says too seriously.', example: 'He tends to exaggerate, so I take everything he says with a grain of salt.', difficulty: 'Medium' },
    { term: 'The whole nine yards', definition: 'Everything, all of it.', example: 'He wanted a new computer with a monitor, keyboard, mouse - the whole nine yards.', difficulty: 'Medium' },
    { term: 'Wouldn\'t be caught dead', definition: 'Would never like to do something because it\'s embarrassing.', example: 'I wouldn\'t be caught dead wearing an outfit like that.', difficulty: 'Medium' },
    { term: 'Your guess is as good as mine', definition: 'To have no idea what the answer is.', example: 'When will the train arrive? Your guess is as good as mine.', difficulty: 'Medium' },
    { term: 'A penny saved is a penny earned', definition: 'By saving money, you are increasing your wealth.', example: 'I\'m putting 10% of my paycheck into savings because a penny saved is a penny earned.', difficulty: 'Medium' },

    // --- HARD ---
    { term: 'The best of both worlds', definition: 'An ideal situation.', example: 'Working from home gives me the best of both worlds: a career and time with my family.', difficulty: 'Hard' },
    { term: 'Once in a blue moon', definition: 'Happens very rarely.', example: 'I only go to the opera once in a blue moon.', difficulty: 'Hard' },
    { term: 'The elephant in the room', definition: 'A major problem that is obviously present but avoided as a subject for discussion.', example: 'His gambling addiction was the elephant in the room at every family gathering.', difficulty: 'Hard' },
    { term: 'Cut corners', definition: 'To do something in the easiest, cheapest, or fastest way.', example: 'The company cut corners on safety regulations and now faces a lawsuit.', difficulty: 'Hard' },
    { term: 'Jump on the bandwagon', definition: 'To join a popular activity or trend.', example: 'After the team won the championship, thousands of new fans jumped on the bandwagon.', difficulty: 'Hard' },
    { term: 'Read between the lines', definition: 'To understand the hidden meaning in what is said or written.', example: 'She said she was fine, but reading between the lines, I could tell she was upset.', difficulty: 'Hard' },
    { term: 'Steal someone\'s thunder', definition: 'To take the credit for something someone else did.', example: 'My colleague stole my thunder when he presented my idea to the boss as his own.', difficulty: 'Hard' },
    { term: 'A leopard can\'t change its spots', definition: 'Used to say that someone\'s character will not change, even if they try.', example: 'I told him he should be more generous, but a leopard can\'t change its spots.', difficulty: 'Hard' },
    { term: 'Throw in the towel', definition: 'To give up or admit defeat.', example: 'After hours of trying to fix the code, the programmer finally threw in the towel.', difficulty: 'Hard' },
    { term: 'The writing is on the wall', definition: 'A sign that something bad is about to happen; a warning of failure.', example: 'When the company lost its biggest client, the writing was on the wall.', difficulty: 'Hard' },
    { term: 'To be long in the tooth', definition: 'To be old.', example: 'He\'s a bit long in the tooth to be starting a new career as a firefighter.', difficulty: 'Hard' },
    { term: 'A flash in the pan', definition: 'Something that is successful only for a short time and is not repeated.', example: 'His first album was a hit, but it turned out to be just a flash in the pan.', difficulty: 'Hard' },
    { term: 'Bury your head in the sand', definition: 'To ignore or avoid a problem, hoping it will go away.', example: 'You can\'t just bury your head in the sand; you have to deal with this issue.', difficulty: 'Hard' },
    { term: 'At the drop of a hat', definition: 'Without any hesitation; instantly.', example: 'If you need help, just call me. I can be there at the drop of a hat.', difficulty: 'Hard' },
    { term: 'Bite the dust', definition: 'To fail, die, or come to an end.', example: 'My old computer finally bit the dust.', difficulty: 'Hard' },
    { term: 'Don\'t count your chickens before they hatch', definition: 'Don\'t make plans for something that might not happen.', example: 'You might get the job, but don\'t count your chickens before they hatch.', difficulty: 'Hard' },
    { term: 'Elvis has left the building', definition: 'The show has come to an end; it\'s all over.', example: 'The concert was over, the lights came on, and we knew Elvis has left the building.', difficulty: 'Hard' },
    { term: 'Method to my madness', definition: 'A purpose in what one is doing, even though it seems crazy.', example: 'My desk is messy, but there is a method to my madness.', difficulty: 'Hard' },
    { term: 'Not playing with a full deck', definition: 'Someone who lacks intelligence or is mentally unstable.', example: 'He keeps talking to himself; I think he\'s not playing with a full deck.', difficulty: 'Hard' },
    { term: 'Saved by the bell', definition: 'Saved from a difficult situation at the last possible moment.', example: 'I was about to give the wrong answer, but then the teacher was interrupted. Saved by the bell!', difficulty: 'Hard' },
    { term: 'Take a rain check', definition: 'To politely decline an offer now, with the hope of accepting it later.', example: 'I can\'t go to dinner tonight, but can I take a rain check?', difficulty: 'Hard' },
    { term: 'The devil is in the details', definition: 'Small, seemingly insignificant things can cause the biggest problems.', example: 'The plan looks good, but the devil is in the details.', difficulty: 'Hard' },
    { term: 'Up in the air', definition: 'Plans are uncertain or unsure.', example: 'Our travel plans are still up in the air; we don\'t know where we\'re going yet.', difficulty: 'Hard' },

    // --- EXAM ---
    { term: 'A dime a dozen', definition: 'Very common and of no particular value.', example: 'Experts in that field are a dime a dozen.', difficulty: 'Exam' },
    { term: 'Cry over spilt milk', definition: 'To be unhappy about something that cannot be undone.', example: 'It\'s no use crying over spilt milk; the mistake is made and we have to move on.', difficulty: 'Exam' },
    { term: 'Get a taste of your own medicine', definition: 'To be treated in the same unpleasant way you have treated others.', example: 'The bully finally got a taste of his own medicine when the new student stood up to him.', difficulty: 'Exam' },
    { term: 'Let sleeping dogs lie', definition: 'To avoid restarting a conflict or argument.', example: 'I wanted to bring up our old argument, but I decided to let sleeping dogs lie.', difficulty: 'Exam' },
    { term: 'Miss the boat', definition: 'To miss an opportunity.', example: 'The tickets sold out in an hour, and I totally missed the boat.', difficulty: 'Exam' },
    { term: 'Through thick and thin', definition: 'Under all circumstances, no matter how difficult.', example: 'True friends stick together through thick and thin.', difficulty: 'Exam' },
    { term: 'Throw caution to the wind', definition: 'To take a risk.', example: 'She threw caution to the wind and quit her job to start her own business.', difficulty: 'Exam' },
    { term: 'Cross the Rubicon', definition: 'To make an irreversible decision or take a decisive step.', example: 'When he submitted his resignation, he knew he had crossed the Rubicon.', difficulty: 'Exam' },
    { term: 'A Pyrrhic victory', definition: 'A victory that comes at such a great cost that it is tantamount to defeat.', example: 'The company won the lawsuit, but it was a Pyrrhic victory that bankrupted them.', difficulty: 'Exam' },
    { term: 'Bury the hatchet', definition: 'To end a conflict and make peace.', example: 'After years of feuding, the two brothers finally decided to bury the hatchet.', difficulty: 'Exam' },
    { term: 'Keep one\'s cards close to one\'s chest', definition: 'To be secretive about one\'s plans or intentions.', example: 'The CEO kept his cards close to his chest regarding the upcoming merger.', difficulty: 'Exam' },
    { term: 'Run the gauntlet', definition: 'To endure a series of criticisms or attacks.', example: 'The new CEO had to run the gauntlet of angry shareholders at the meeting.', difficulty: 'Exam' },
    { term: 'Wild-goose chase', definition: 'A foolish and hopeless pursuit of something unattainable.', example: 'The detective realized he had been sent on a wild-goose chase.', difficulty: 'Exam' },
    { term: 'A wolf in sheep\'s clothing', definition: 'A person who pretends to be harmless or friendly but is actually hostile.', example: 'The unctuous salesperson was a wolf in sheep\'s clothing.', difficulty: 'Exam' },
    { term: 'A sea change', definition: 'A profound or notable transformation.', example: 'The internet has brought about a sea change in how we consume media.', difficulty: 'Exam' },
    { term: 'The sword of Damocles', definition: 'A constantly threatening danger.', example: 'With the final exams approaching, the sword of Damocles hung over the students.', difficulty: 'Exam' },
    { term: 'Fiddle while Rome burns', definition: 'To occupy oneself with unimportant matters and neglect priorities during a crisis.', example: 'The manager was organizing his desk while the company was going bankrupt; he was fiddling while Rome burns.', difficulty: 'Exam' },
    { term: 'Meet your Waterloo', definition: 'To encounter your final, decisive defeat.', example: 'The chess champion met his Waterloo in the final match against the young prodigy.', difficulty: 'Exam' },
    { term: 'A Trojan horse', definition: 'Something or someone that is intended to defeat or subvert from within.', example: 'The free software was a Trojan horse that installed malware on his computer.', difficulty: 'Exam' },
    { term: 'The Midas touch', definition: 'The ability to make money or be successful at everything one does.', example: 'Everything she invests in turns a profit; she truly has the Midas touch.', difficulty: 'Exam' },
    { term: 'An Achilles\' heel', definition: 'A weakness or vulnerable point.', example: 'His quick temper is his Achilles\' heel.', difficulty: 'Exam' },
    { term: 'Leave no stone unturned', definition: 'To try every possible course of action in order to achieve something.', example: 'The detectives left no stone unturned in their search for the missing child.', difficulty: 'Exam' },
    { term: 'Rest on your laurels', definition: 'To be so satisfied with what you have already done that you do not try to achieve anything new.', example: 'Even after winning the championship, the coach told the team not to rest on their laurels.', difficulty: 'Exam' },
    { term: 'Paint the town red', definition: 'To go out and enjoy oneself flamboyantly.', example: 'After their final exams, the students went out to paint the town red.', difficulty: 'Exam' },
];