// @/database/quotes.ts
import { Quote } from '../types';

export const quotes: Quote[] = [
    { quote: "The beautiful thing about learning is that no one can take it away from you.", author: "B.B. King" },
    { quote: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
    { quote: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle" },
    { quote: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
    { quote: "The only person who is educated is the one who has learned how to learn and change.", author: "Carl Rogers" },
    { quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
    { quote: "It is not that I'm so smart. But I stay with the questions much longer.", author: "Albert Einstein" },
    { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { quote: "The expert in anything was once a beginner.", author: "Helen Hayes" },
    { quote: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
    { quote: "Learning is a treasure that will follow its owner everywhere.", author: "Chinese Proverb" },
    { quote: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { quote: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
    { quote: "The mind is not a vessel to be filled, but a fire to be kindled.", author: "Plutarch" },
    { quote: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin" },
    { quote: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
    { quote: "He who opens a school door, closes a prison.", author: "Victor Hugo" },
    { quote: "Education is not preparation for life; education is life itself.", author: "John Dewey" },
    { quote: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
    { quote: "The more that you read, the more things you will know. The more that you learn, the more places you'll go.", author: "Dr. Seuss" },
    { quote: "Learning never exhausts the mind.", author: "Leonardo da Vinci" },
    { quote: "The goal of education is the advancement of knowledge and the dissemination of truth.", author: "John F. Kennedy" },
    { quote: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle" },
    { quote: "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.", author: "Albert Einstein" },
    { quote: "I have no special talent. I am only passionately curious.", author: "Albert Einstein" },
    { quote: "The art of teaching is the art of assisting discovery.", author: "Mark Van Doren" },
    { quote: "Change is the end result of all true learning.", author: "Leo Buscaglia" },
    { quote: "Education's purpose is to replace an empty mind with an open one.", author: "Malcolm Forbes" },
    { quote: "Anyone who stops learning is old, whether at twenty or eighty. Anyone who keeps learning stays young.", author: "Henry Ford" },
    { quote: "The only thing that interferes with my learning is my education.", author: "Albert Einstein" },
    { quote: "Knowledge is power.", author: "Francis Bacon" },
    { quote: "What we learn with pleasure we never forget.", author: "Alfred Mercier" },
    { quote: "The highest result of education is tolerance.", author: "Helen Keller" },
    { quote: "The foundation of every state is the education of its youth.", author: "Diogenes" },
    { quote: "You are always a student, never a master. You have to keep moving forward.", author: "Conrad Hall" },
    { quote: "I am still learning.", author: "Michelangelo" },
    { quote: "Strive for progress, not perfection.", author: "Unknown" },
    { quote: "There is no substitute for hard work.", author: "Thomas Edison" },
    { quote: "Do the best you can until you know better. Then when you know better, do better.", author: "Maya Angelou" },
    { quote: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.", author: "Thomas Edison" },
    { quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { quote: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
    { quote: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison" },
    { quote: "If you can dream it, you can do it.", author: "Walt Disney" },
    { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { quote: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
    { quote: "Either you run the day or the day runs you.", author: "Jim Rohn" },
    { quote: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
    { quote: "The best way to predict the future is to create it.", author: "Peter Drucker" },
    { quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
    { quote: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
    { quote: "You have to be odd to be number one.", author: "Dr. Seuss" },
    { quote: "Fall seven times and stand up eight.", author: "Japanese Proverb" },
    { quote: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
    { quote: "I would rather die of passion than of boredom.", author: "Vincent van Gogh" },
    { quote: "It is never too late to be what you might have been.", author: "George Eliot" },
    { quote: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
    { quote: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { quote: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
    { quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
    { quote: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
    { quote: "The man who has confidence in himself gains the confidence of others.", author: "Hasidic Proverb" },
    { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
    { quote: "The secret of change is to focus all of your energy, not on fighting the old, but on building the new.", author: "Socrates" },
    { quote: "A creative man is motivated by the desire to achieve, not by the desire to beat others.", author: "Ayn Rand" },
    { quote: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
    { quote: "The most difficult thing is the decision to act, the rest is merely tenacity.", author: "Amelia Earhart" },
    { quote: "Whether you think you can or you think you can’t, you’re right.", author: "Henry Ford" },
    { quote: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain" },
    { quote: "Nothing is impossible, the word itself says 'I'm possible'!", author: "Audrey Hepburn" },
    { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { quote: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
    { quote: "All our dreams can come true if we have the courage to pursue them.", author: "Walt Disney" },
    { quote: "Don't let what you cannot do interfere with what you can do.", author: "John Wooden" },
    { quote: "If you're going through hell, keep going.", author: "Winston Churchill" },
    { quote: "In order to succeed, we must first believe that we can.", author: "Nikos Kazantzakis" },
    { quote: "Never bend your head. Always hold it high. Look the world straight in the eye.", author: "Helen Keller" },
    { quote: "What you do today can improve all your tomorrrows.", author: "Ralph Marston" },
    { quote: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
    { quote: "Education is the passport to the future, for tomorrow belongs to those who prepare for it today.", author: "Malcolm X" },
    { quote: "The function of education is to teach one to think intensively and to think critically. Intelligence plus character - that is the goal of true education.", author: "Martin Luther King, Jr." },
    { quote: "The cure for boredom is curiosity. There is no cure for curiosity.", author: "Dorothy Parker" },
    { quote: "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.", author: "Brian Herbert" },
    { quote: "One child, one teacher, one book, one pen can change the world.", author: "Malala Yousafzai" },
    { quote: "Never memorize something that you can look up.", author: "Albert Einstein" },
    { quote: "Education is not the filling of a pail, but the lighting of a fire.", author: "W.B. Yeats" },
    { quote: "The beautiful thing about learning is that nobody can take it away from you.", author: "B.B. King" },
    { quote: "Study without desire spoils the memory, and it retains nothing that it takes in.", author: "Leonardo da Vinci" },
    { quote: "By all means, marry. If you get a good wife, you'll become happy; if you get a bad one, you'll become a philosopher.", author: "Socrates" },
    { quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
    { quote: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", author: "Albert Einstein" },
    { quote: "So many books, so little time.", author: "Frank Zappa" },
    { quote: "A room without books is like a body without a soul.", author: "Marcus Tullius Cicero" },
    { quote: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
    { quote: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
    { quote: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
    { quote: "If you tell the truth, you don't have to remember anything.", author: "Mark Twain" },
    { quote: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
    { quote: "Without music, life would be a mistake.", author: "Friedrich Nietzsche" },
    { quote: "It is not a lack of love, but a lack of friendship that makes unhappy marriages.", author: "Friedrich Nietzsche" },
    { quote: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
    { quote: "The fool doth think he is wise, but the wise man knows himself to be a fool.", author: "William Shakespeare" },
    { quote: "Whenever you find yourself on the side of the majority, it is time to reform (or pause and reflect).", author: "Mark Twain" },
    { quote: "Good friends, good books, and a sleepy conscience: this is the ideal life.", author: "Mark Twain" },
    { quote: "The man who does not read has no advantage over the man who cannot read.", author: "Mark Twain" },
    { quote: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde" },
    { quote: "I can resist everything except temptation.", author: "Oscar Wilde" },
    { quote: "Always forgive your enemies; nothing annoys them so much.", author: "Oscar Wilde" },
    { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { quote: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
    { quote: "If life were predictable it would cease to be life, and be without flavor.", author: "Eleanor Roosevelt" },
    { quote: "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.", author: "Oprah Winfrey" },
    { quote: "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.", author: "James Cameron" },
    { quote: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
    { quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
    { quote: "Well done is better than well said.", author: "Benjamin Franklin" },
    { quote: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
    { quote: "Whoever is happy will make others happy too.", author: "Anne Frank" },
    { quote: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
    { quote: "You will face many defeats in life, but never let yourself be defeated.", author: "Maya Angelou" },
    { quote: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
    { quote: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.", author: "Dr. Seuss" },
    { quote: "Life is a succession of lessons which must be lived to be understood.", author: "Helen Keller" },
    { quote: "Curiosity about life in all of its aspects, I think, is still the secret of great creative people.", author: "Leo Burnett" },
    { quote: "Life is not a problem to be solved, but a reality to be experienced.", author: "Soren Kierkegaard" },
    { quote: "The unexamined life is not worth living.", author: "Socrates" },
    { quote: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
    { quote: "The way I see it, if you want the rainbow, you gotta put up with the rain.", author: "Dolly Parton" },
    { quote: "Everything has beauty, but not everyone sees it.", author: "Confucius" },
    { quote: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
    { quote: "In this life we cannot do great things. We can only do small things with great love.", author: "Mother Teresa" },
    { quote: "Only a life lived for others is a life worthwhile.", author: "Albert Einstein" },
    { quote: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", author: "Ralph Waldo Emerson" },
    { quote: "I'm a success today because I had a friend who believed in me and I didn't have the heart to let him down.", author: "Abraham Lincoln" },
    { quote: "You can't use up creativity. The more you use, the more you have.", author: "Maya Angelou" },
    { quote: "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.", author: "Helen Keller" },
    { quote: "It is our choices that show what we truly are, far more than our abilities.", author: "J.K. Rowling" },
    { quote: "If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.", author: "J.K. Rowling" },
    { quote: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot" },
    { quote: "A river cuts through rock, not because of its power, but because of its persistence.", author: "Jim Watkins" },
    { quote: "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.", author: "Vince Lombardi" },
    { quote: "Permanence, perseverance and persistence in spite of all obstacles, discouragements, and impossibilities: It is this, that in all things distinguishes the strong soul from the weak.", author: "Thomas Carlyle" },
    { quote: "The oak fought the wind and was broken, the willow bent when it must and survived.", author: "Robert Jordan" },
    { quote: "Resilience is accepting your new reality, even if it's less good than the one you had before.", author: "Elizabeth Edwards" },
    { quote: "Do not judge me by my success, judge me by how many times I fell down and got back up again.", author: "Nelson Mandela" },
    { quote: "I can be changed by what happens to me. But I refuse to be reduced by it.", author: "Maya Angelou" },
    { quote: "Perseverance is failing 19 times and succeeding the 20th.", author: "Julie Andrews" },
    { quote: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
    { quote: "The greatest oak was once a little nut who held its ground.", author: "Author Unknown" },
    { quote: "Persistence is to the character of man as carbon is to steel.", author: "Napoleon Hill" },
    { quote: "Continuous effort – not strength or intelligence – is the key to unlocking our potential.", author: "Winston S. Churchill" },
    { quote: "Honesty is the first chapter in the book of wisdom.", author: "Thomas Jefferson" },
    { quote: "No legacy is so rich as honesty.", author: "William Shakespeare" },
    { quote: "The elegance of honesty needs no adornment.", author: "Merry Browne" },
    { quote: "Honesty is the best policy.", author: "Benjamin Franklin" },
    { quote: "Honesty and transparency make you vulnerable. Be honest and transparent anyway.", author: "Mother Teresa" },
    { quote: "To be persuasive we must be believable; to be believable we must be credible; to be credible we must be truthful.", author: "Edward R. Murrow" },
    { quote: "No matter how educated, talented, rich, or cool you believe you are, how you treat people ultimately tells all. Integrity is everything.", author: "Unknown" },
    { quote: "Integrity is telling myself the truth. And honesty is telling the truth to other people.", author: "Spencer Johnson" },
    { quote: "Truth never damages a cause that is just.", author: "Mahatma Gandhi" },
    { quote: "If you do not tell the truth about yourself you cannot tell it about other people.", author: "Virginia Woolf" },
    { quote: "It is difficult, but not impossible, to conduct strictly honest business.", author: "Mahatma Gandhi" },
    { quote: "It takes strength and courage to admit the truth.", author: "Rick Riordan" },
    { quote: "I am a slow walker, but I never walk back.", author: "Abraham Lincoln" },
    { quote: "Patience and perseverance have a magical effect before which difficulties disappear and obstacles vanish.", author: "John Quincy Adams" },
    { quote: "Champions keep playing until they get it right.", author: "Billie Jean King" },
    { quote: "It’s hard to beat a person who never gives up.", author: "Babe Ruth" },
    { quote: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" }
];
